# Generated by Django 5.1.2 on 2024-10-31 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Users',
            new_name='user',
        ),
    ]
