# Generated by Django 5.0.1 on 2024-10-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_vote_ratio_alter_project_vote_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Project',
            new_name='project',
        ),
    ]
